package postmark

// ErrorLookup defines the meaning of all Postmark error codes
// For future reference, these were parsed by copy-and-pasting the following webpage:
// http://developer.postmarkapp.com/developer-api-overview.html#error-codes
// using this regex: /(\d+) — (.*)\n.*/
// and this output format: /\t$1: "$2",/
var ErrorLookup = map[int]string{
	10:   "Bad or missing API token",
	100:  "Maintenance",
	300:  "Invalid email request",
	400:  "Sender Signature not found",
	401:  "Sender signature not confirmed",
	402:  "Invalid JSON",
	403:  "Incompatible JSON",
	405:  "Not allowed to send",
	406:  "Inactive recipient",
	409:  "JSON required",
	410:  "Too many batch messages",
	411:  "Forbidden attachment type",
	500:  "Sender signature query exception",
	501:  "Sender Signature not found by id",
	502:  "No updated Sender Signature data received",
	503:  "You cannot use a public domain",
	504:  "Sender Signature already exists",
	505:  "DKIM already scheduled for renewal",
	506:  "This Sender Signature already confirmed",
	507:  "You do not own this Sender Signature",
	520:  "You are missing a required field to create a Sender Signature.",
	521:  "A field in the Sender Signature request is too long.",
	522:  "Value for field is invalid.",
	600:  "Server query exception",
	601:  "Server does not exist",
	602:  "Duplicate Inbound Domain",
	603:  "Server name already exists",
	604:  "You don’t have delete access",
	605:  "Unable to delete Server",
	606:  "Invalid webhook URL",
	607:  "Invalid Server color",
	608:  "Server name missing or invalid",
	609:  "No updated Server data received",
	610:  "Invalid MX record for Inbound Domain",
	611:  "InboundSpamThreshold value is invalid. Please use a number between 0 and 30 in incrememts of 5.",
	700:  "Messages query exception",
	701:  "Message doesn’t exist",
	702:  "Could not bypass this blocked inbound message, please contact support.",
	703:  "Could not retry this failed inbound message, please contact support.",
	800:  "Trigger query exception",
	801:  "Trigger for this tag doesn’t exist",
	803:  "Tag with this name already has trigger associated with it",
	808:  "Name to match is missing",
	809:  "No trigger data received",
	810:  "This inbound rule already exists.",
	811:  "Unable to remove this inbound rule, please contact support.",
	812:  "This inbound rule was not found.",
	813:  "Not a valid email address or domain.",
	900:  "Stats query exception",
	1000: "Bounces query exception",
	1001: "Bounce was not found.",
	1002: "BounceID parameter required.",
	1003: "Cannot activate bounce.",
	1100: "Template query exception.",
	1101: "TemplateId not found.",
	1105: "Template Limit would be Exceeded.",
	1109: "No Template data received.",
	1120: "A required Template field is missing.",
	1121: "Template field is too large.",
	1122: "A Templated field has been submitted that is invalid.",
	1123: "A field was included in the request body that is not allowed.",
}
